### ISSUE TITLE
Problems with saving files

### ISSUE THREAD

**Issue by hope366** [CamWagner/lizzie#786]
When saving a file in lizzie, `*.sgf` is specified by default.
If you save the file in this state, it will be saved as a `.sgf` file, but when you save another new file, you won't be able to see previously saved files of the `.sgf` format.
The `*` doesn't seem to be necessary. What is the purpose of `*`?

**Comment by kaorahi** [comment]
How about making a pull request by yourself? I think this is a good chance. :-)

1. Search `*.sgf` in the source code. You will find `FileNameExtensionFilter`.
2. Search `FileNameExtensionFilter` in the Internet. You will find a document, e.g. https://docs.oracle.com/javase/jp/8/docs/api/javax/swing/filechooser/FileNameExtensionFilter.html .
3. Read it, correct the wrong code, and make a pull request. Search "github pull request" in the Internet if you need.

**Comment by hope366** [comment]
Thank you.
I'm not confident, but I'll give it a try.

**Comment by NTUST-MITLAB** [comment]
> Thank you.
> I'm not confident, but I'll give it a try.

It's in the `MainFrame.java` at the first line of the `public void saveFile()`, change it to `FileNameExtensionFilter filter = new FileNameExtensionFilter("sgf file", "sgf", "SGF");` 
The first "sgf file" is the description of the file extension, you can give it any proper description (like "Smart Game Format *.sgf files"), the followings are actual file extensions.

And I found a minor bug, at
```
      if (!file.getPath().endsWith(".sgf")) {
        file = new File(file.getPath() + ".sgf");
      }
```
So if the game file extension is upper case SGF, and you click the file with that upper case extension, although the pop-up warning says it would overwrite the file, it actually creates a new .SGF.sgf file.

**Comment by hope366** [comment]
Oh, what a thing to say!
I didn't know that slight change would solve the problem!
I've been racking my brain about it from morning to night today.
I can compile lizzie using source code written by others, but I don't know anything about programming.For the first time today, I learned even the rudimentary thing that the java file name must be the same as the class name.
[here](https://docs.oracle.com/javase/jp/8/docs/api/javax/swing/filechooser/FileNameExtensionFilter.html), despite the fact that I had the following exemplary answers I couldn't master it...
But it's very nice to know something new

`FileFilter filter = new FileNameExtensionFilter("JPEG file", "jpg", "jpeg");`

**Comment by NTUST-MITLAB** [comment]
> Oh, what a thing to say!
> I didn't know that slight change would solve the problem!
> I've been racking my brain about it from morning to night today.
> I can compile lizzie using source code written by others, but I don't know anything about programming. Today I learned for the first time that you have to specify a class file when compiling with `javac` and other rudimentary things.
> [here](https://docs.oracle.com/javase/jp/8/docs/api/javax/swing/filechooser/FileNameExtensionFilter.html), despite the fact that I had the following exemplary answers I couldn't master it...
> But it's very nice to know something new
> 
> `FileFilter filter = new FileNameExtensionFilter("JPEG file", "jpg", "jpeg");`

Lots of time, debugging is just reading how to properly call a function, and the proper parameters to call it. But the difficult ones involve tracking the logic and lots of flags and print variables to figure out what actually been changed under the hood. 

I think the save and load upper case SGF extension file is more about the logic debugging. Need to change the condition to include both .sgf and .SGF in both functions to
 saveFile() 
```
      if (!(file.getPath().endsWith(".sgf") || file.getPath().endsWith(".SGF"))) {
        file = new File(file.getPath() + ".sgf");
      }
```
and loadFile(). 
```
if (file.getPath().endsWith(".sgf") || file.getPath().endsWith(".SGF")) {
        SGFParser.load(file.getPath());
```

Although I am not familiar with the whole framework enough to know if other places need to have some associated modifications to solve this bug fully, like in the SGFParser, or even GIBParser to handle exceptions or wrong formats.

**Comment by hope366** [comment]
I tried replacing the given positions in `saveFile ()` and `loadFile ().` with the ones presented.
A file called .SGF.sgf was not generated and the .SGF file was overwritten.
However, opening the overwritten .SGF file is unresponsive. lizzie seems to refuse.
In the first place, the .SGF file itself, which is not overwritten and exists from the beginning, seems to be rejected by lizzie.
I don't feel inconvenienced because I usually use only .sgf files, but I want it to be loaded normally because it has .SGF notation.

As the next problem ...
mainframe.java has items called openFile and loadFile.
I think that the operation of openFile in lizzie is "o" key or "File"-> "Open". What is loadFile?
Do you mean "File"-> "Open from URL"? I have never done this operation. Is there a game record that can be opened from the URL? Where can I find such a URL?

**Comment by NTUST-MITLAB** [comment]
> I tried replacing the given positions in `saveFile ()` and `loadFile ().` with the ones presented.
> A file called .SGF.sgf was not generated and the .SGF file was overwritten.
> However, opening the overwritten .SGF file is unresponsive. lizzie seems to refuse.
> In the first place, the .SGF file itself, which is not overwritten and exists from the beginning, seems to be rejected by lizzie.
> I don't feel inconvenienced because I usually use only .sgf files, but I want it to be loaded normally because it has .SGF notation.
> 
> As the next problem ...
> mainframe.java has items called openFile and loadFile.
> I think that the operation of openFile in lizzie is "o" key or "File"-> "Open". What is loadFile?
> Do you mean "File"-> "Open from URL"? I have never done this operation. Is there a game record that can be opened from the URL? Where can I find such a URL?

I think before the try {} catch _{} the previous if statement also need to exclude SGF and probably GIB upper case extension files,
```
    if (!(file.getPath().endsWith(".sgf")
        || file.getPath().endsWith(".gib")
        || file.getPath().endsWith(".SGF")
        || file.getPath().endsWith(".GIB"))) {
      file = new File(file.getPath() + ".sgf");
    }
``` 
I haven't fully tested or follow through with all the relevant codes, so not sure if these are all that need to fix it (the more familiar with the code structure, the less needing to tracing them). The original code works to a degree because it never recognizes the upper case extension, so those files never showed up in the dialog windows unless you specifically select showing all files, hence this bug is hidden for the most part (an upper case file in the original code cannot be loaded, and it was always saved to a lower case extension file). And there might be a potential compatibility issue with how Windows handles extension and how Linux handles extension.

For the second question, openFile function called loadFile function. openFile handles the dialog window (create the object), loadFile is the actual code behind the scene to load the file and send it to Parser functions (SGFParser and GIBParser) to interpret them. This is why you need to trace codes, when something is modified, it might have effects on other parts. And openFile is a public method for the MainFrame class for handling open file dialog. The Open from URL menu actually calls a different function openOnlineDialog which has a completely different class OnlineDialog to handle it (instead of the FileDialog class, which is from a native Java GUI library). Welcome to the fun of OOP and debugging. 

And to the final question, yes, you can open an URL that contains an updating live game, like the final Meijin title match last week on yikeweiqi [https://api.yikeweiqi.com/golive/dtl?id=54116](https://api.yikeweiqi.com/golive/dtl?id=54116) through API or normal URL [https://home.yikeweiqi.com/#/live/room/54116/1/48672443](https://home.yikeweiqi.com/#/live/room/54116/1/48672443). the OnlineDialog class has parsers to recognize the URL and their contents.

**Comment by hope366** [comment]
Thanks for giving me the URL to load the game.
> if (! (file.getPath().endsWith(".sgf")
        || file.getPath().endsWith(".gib")
        || file.getPath().endsWith(".SGF")
        || file.getPath().endsWith(".GIB"))) {
      file = new File(file.getPath() + ".sgf");
    }

I tried using this in the loadFile section, but the .SGF file seems to be failing to load as before...
Computer programs seem deep and interesting, but that's what makes them so difficult.

**Comment by NTUST-MITLAB** [comment]
> Thanks for giving me the URL to load the game.
> 
> > if (! (file.getPath().endsWith(".sgf")
> > || file.getPath().endsWith(".gib")
> > || file.getPath().endsWith(".SGF")
> > || file.getPath().endsWith(".GIB"))) {
> > file = new File(file.getPath() + ".sgf");
> > }
> 
> I tried using this in the loadFile section, but the .SGF file seems to be failing to load as before...
> Computer programs seem deep and interesting, but that's what makes them so difficult.

Normally, when you run into a conditional check, and not sure if it is properly triggered, you can use print out to assist you in debugging.
```
    if (!(file.getPath().endsWith(".sgf")
        || file.getPath().endsWith(".gib")
        || file.getPath().endsWith(".SGF")
        || file.getPath().endsWith(".GIB"))) {
      System.out.println(
          "ended with non-supported file extensions, added lower-case sgf extension as default");
      file = new File(file.getPath() + ".sgf");
    }
```
And start Lizzie with a console (or command prompt, depend on your platform) with `java -jar lizzie-0.7.4-shaded.jar`
Open a file with upper case SGF file extension in the dialog window by clicking the file, and then check the console output. There is already a print out for `file.getPath()` so you can tell exactly which String is used as the path to the file to load it. If it is correct, there shouldn't have this debug message appear in the console output. 

Also do another test, where you type in the file name of the upper case extension (like if it is `test.SGF`, just type in `test`), then this debug message should appear before the `file.getPath()` get print out. The purpose of this condition is to simply add a file extension since in some system and some settings the file extension is not shown by default. If this is the case that means when you click the file in the dialog window, its extension name is not sent to the getPath(), wherein some systems, they treated upper and lower case extension differently (in most Windows system they are the same). This is what I was talking about the potential compatibility issues in this simple file handling code.

**Comment by hope366** [comment]
>    if (!(file.getPath().endsWith(".sgf")
        || file.getPath().endsWith(".gib")
        || file.getPath().endsWith(".SGF")
        || file.getPath().endsWith(".GIB"))) {
      System.out.println(
          "ended with non-supported file extensions, added lower-case sgf extension as default");
      file = new File(file.getPath() + ".sgf");
    }

I applied this and tried loading the .SGF file.
It looks like the screenshot below.
It seems that the value of komi has been changed to 1.5 for some reason. This was not the case with the official release version.
![無題](https://user-images.githubusercontent.com/63999713/96424234-657a1b80-1235-11eb-914b-095dd2fd120d.png)

**Comment by hope366** [comment]
There is a game record called "WorldAI-LZvsGOLAXY.SGF", but when I opened the file, I typed "WorldAI-LZvsGOLAXY" and loaded it, it looked like the following screenshot.
![無題](https://user-images.githubusercontent.com/63999713/96426282-01a52200-1238-11eb-8f74-9f3639f2b12f.png)

**Comment by NTUST-MITLAB** [comment]
> > if (!(file.getPath().endsWith(".sgf")
> > || file.getPath().endsWith(".gib")
> > || file.getPath().endsWith(".SGF")
> > || file.getPath().endsWith(".GIB"))) {
> > System.out.println(
> > "ended with non-supported file extensions, added lower-case sgf extension as default");
> > file = new File(file.getPath() + ".sgf");
> > }
> 
> I applied this and tried loading the .SGF file.
> It looks like the screenshot below.
> It seems that the value of komi has been changed to 1.5 for some reason. This was not the case with the official release version.
> ![無題](https://user-images.githubusercontent.com/63999713/96424234-657a1b80-1235-11eb-914b-095dd2fd120d.png)

The first set komi should be from the default komi value (which is 7.5), if it is 6.5 it's likely passing the https://github.com/kaorahi/lizzie/commit/63753f2fbb17b94fe583e5687009b98eb91e3d9e `fixFoxSGF` to set it to default 6.5 if it detects it is a game record from foxweiqui. The second set komi should be from the game record itself. If it is parsing the wrong value there are some codes broken in the SGFParser. You can open the game file itself with the editor and search for 1.5, or the source code to see where the 1.5 value came from.

And by the look of it, the if condition and debug message worked as intended. It did as it intended to. The problem should be in the codes following, most likely the SGFParser itself. Or it could be there are some issues with the game format. The patch for fixing fox game records is not fully tested yet, not sure if the fix from https://github.com/featurecat/lizzie/issues/755 actually broke something else, combined with other changes. It might also be related to character encoding. I see that the output file path string has some weird characters that might be the system itself actually store the string in different encoding and mess up with the relative path. Maybe try to generate a simple test game yourself, and put it in a directory without Kanji or Chinese characters in the folder name for the path.

**Comment by NTUST-MITLAB** [comment]
> There is a game record called "WorldAI-LZvsGOLAXY.SGF", but when I opened the file, I typed "WorldAI-LZvsGOLAXY" and loaded it, it looked like the following screenshot.

The only 1.5 komi value is from GIBParser, so to check if it is the problem, try to determine if this is the case with debugging messages print out.
```
      if (file.getPath().endsWith(".sgf") || file.getPath().endsWith(".SGF")) {
        System.out.println("use SGFParser");
        SGFParser.load(file.getPath());
      } else {
        System.out.println("use GIBParser");
        GIBParser.load(file.getPath());
      }
```
See if the file is passed to the wrong parser.

**Comment by hope366** [comment]
The SGF file says "7.5".
![komi](https://user-images.githubusercontent.com/63999713/96440784-69ad3580-1243-11eb-9568-d28ac73325db.png)
I changed the path string to alphabetic, but the bug that changed the value of komi to 1.5 has not been fixed. By the way, this game is not foxweiqui's game, and the default komi value is 6.5 because I changed the source code from 7.5 to 6.5.(6.5 is useful by default.)
![1 5](https://user-images.githubusercontent.com/63999713/96441259-361edb00-1244-11eb-8614-6fe12233f20c.png)

When I added and ran the code to see which parser was used, the value of komi was never 1.5, and it correctly reflected the 7.5 of the game content.
![7 5](https://user-images.githubusercontent.com/63999713/96441425-78e0b300-1244-11eb-8540-edd4b2912b0f.png)

**Comment by NTUST-MITLAB** [comment]
print line shouldn't affect anything. Did you change the way you load the game? Did you try just type in the filename without extension with the added debug message? Or did you click the file in the dialog window?

**Comment by NTUST-MITLAB** [comment]
If there is any doubt that adding the println actually "fixes the problem", try to restore the code to the original, and instead put the error message println inside the first line of SGFParser load function, and GIBParser load function. And see which got called and if the 1.5 komi problem can be recreated.

**Comment by NTUST-MITLAB** [comment]
BTW, do you know how to fork the source code and put your changed codes to your forked depository, it would be easier to check what actually been done, and if there is any grammatical issue causing the problem instead (since I am typing the code in part, not a full diff compare from source to source), a small error in key in, like the wrong bracket placement or insert in the wrong place would have a huge impact, and might not always show up as a compiler error.

**Comment by hope366** [comment]
I tried again, but komi was never changed to 1.5. komi was changed to 7.5, which is the same as the game record, and it says "use SGFParser". It may have been a simple typing error.
When loading the file, I selected the desired file in the dialog box and manually deleted the ".SGF" and set it to "Open".
I'm still unfamiliar with GitHub and I don't think I've gotten a good handle on its features.
I use Visual Studio Code to change the source code, and I have multiple "src" folders on my computer to keep track of them.

**Comment by NTUST-MITLAB** [comment]
In the Dialog window does the file actually has an extension after its name?
![image](https://user-images.githubusercontent.com/43801414/96464296-3924c600-125a-11eb-9213-f613236235d2.png)

Have you tried using Lizzie to play a  few moves, change the komi, change the player names info, etc., and save it to a test.sgf file, manually change the extension to upper case test.SGF using normal means (like a file manager), and reopen it with Lizzie with debugging message codes...

Also, similarly generated a test game, but using Lizzie save dialog and save it with an upper case extension of a different name. And then try to reload it to see if it has issues? And finally, try to open both of them with other software like Sabaki or MultiGo, or even just text editors to see what exactly is stored. All this might give you some clues to what's going on.

**Comment by hope366** [comment]
The file extension is displayed.
![無題](https://user-images.githubusercontent.com/63999713/96471673-8c067980-126a-11eb-9988-be1ea73611a1.png)
After experimenting with the fix code you provided, I also succeeded in loading a file with a .SGF uppercase extension. The same is true for .GIB. However, when saving, only .sgf or .SGF is possible, and if you try to save as .gib or .GIB, it will be forcibly saved in .sgf format like .gib.sgf or .GIB.sgf.
I also have Sabaki and MultiGo, so I would like to try various things.
By the way, I have one question, but this time @kaorahi recommended me to make a pull request. However, it took some time to resolve, and in the meantime you announced a good fix.
I would like to take this opportunity to take on the challenge of "pull request," which is a new attempt for me. I would like to use the 
`FileNameExtensionFilter filter = new FileNameExtensionFilter ("sgf file", "sgf", "SGF"); `
that you provided, can you give me permission?
I forked from featurecat / lizzie to create hope366 / lizzie. I cloned it to my PC to create a branch, committed my modifications and pushed it remotely.
Currently my remote repository looks like this: Is there anything I need to fix?
https://github.com/hope366/lizzie/tree/689b31ebff129bce00db66fbaae6aa3e11d51026

**Comment by NTUST-MITLAB** [comment]
The `GIBParser` is incomplete, it only has load() function and no save() function. Even the SGFParser is somewhat incomplete, lots of properties format not implemented, and not able to load. SGFParse save() also has a few bugs too. Its code is kinda a mess to debug and modify. Still trying to add some function to read different encoding in the sgf.  I actually like a ugi or ugf format parser and converter, there is software like MultiGo can read it, but not able to save it. (like Lizzie's GIBParser), the problem is its encoding is in Shift_JIS, which isn't very popular outside of Japan.

I personally think maybe it is better to stick with lower case sgf for the moment with the save function FileNameExtensionFilter, it has less impact to the current codes, hide the minor bug of reading upper case extension for the moment, before all the related SGFParser issues of save/load have been resolved.
`    FileNameExtensionFilter filter = new FileNameExtensionFilter("Smart Game Format (*.sgf *.SGF)", "sgf");`

**Comment by hope366** [comment]
I was successful in loading the uppercase .SGF file, but that was after applying a number of PRs to the official version of lizzie 0.7.4.
I tried to verify whether it works properly when only the modification related to this extension is added to the official version of lizzie 0.7.4.
Surprisingly, when I loaded the uppercase .SGF file, komi was changed to the 1.5th and the result was that GIBParser was used.
At the moment, it's unclear why this happened.
Some time ago, it was reported that when a file with analysis results was loaded with lizzie 0.7.4, the analysis results were not displayed, but lizzie with a number of PRs applied did not have that problem. It seems that a change in one part of the code can lead to other problems that are completely unexpected. I thought this case was similar. Computer programs are a tricky thing.
The changes made in the loadFile item are as follows.
>    if (!(file.getPath().endsWith(".sgf")
        || file.getPath().endsWith(".gib")
        || file.getPath().endsWith(".SGF")
        || file.getPath().endsWith(".GIB"))) {
      System.out.println(
          "ended with non-supported file extensions, added lower-case sgf extension as default");
      file = new File(file.getPath() + ".sgf");
    }

>if (file.getPath().endsWith(".sgf") || file.getPath().endsWith(".SGF")) {
        SGFParser.load(file.getPath());

>if (file.getPath().endsWith(".sgf") || file.getPath().endsWith(".SGF")) {
    System.out.println("use SGFParser");
    SGFParser.load(file.getPath());
   } else {
    System.out.println("use GIBParser");
    GIBParser.load(file.getPath());
   }

![無題](https://user-images.githubusercontent.com/63999713/96535476-dcaebe80-12cc-11eb-8627-660a2248973b.png)
