### ISSUE TITLE
Leela 0.11.0 on Lizzie 0.7.4

### ISSUE THREAD

**Issue by kaorahi** [CamWagner/lizzie#815]
Leela 0.11.0 (not Leela Zero) was once supported in #182. But it was deleted in #247 silently before Lizzie 0.5. So I made a quick hack to support Leela 0.11.0 on Lizzie 0.7.4 again. You can set `leela_gtp -g` as the engine command. Does anybody want to use this seriously? (It is not tested at all.)

https://github.com/kaorahi/lizzie/tree/leela_nonzero_on074

**Comment by hope366** [comment]
I tried "leela_nonzero_on074".
I placed "Leela0110GTP.exe" in the lizzie folder and set the engine command to "Leela0110GTP.exe -g".
It seems that it started normally, but the candidate move is not displayed on the board.
Previously, there was a person who wanted to use Leela 0.11.0 with lizzie. However, it was a story that assumed that candidates would be displayed like Leela Zero and Kata Go.
Is it possible to program to display candidate moves?

**Comment by kaorahi** [comment]
It works for me...

![leela0110](https://user-images.githubusercontent.com/38910552/99387226-f9173880-2916-11eb-996c-cbde8b06cb2e.png)

1. If you merge f8c43713 with my other patches, you may need some edits of the code to resolve conflicts. Would you try the above URL itself first?
2. What is shown on the GTP console?

**Comment by hope366** [comment]
I tried [`f8c4371`](https://github.com/featurecat/lizzie/commit/f8c43713709b84c1e39b9790a07ef1bd28702d87) (Alone) 
But no candidate moves are displayed on the board.
Turning on pondering puts a load on the computer, so it seems to be working internally.
The GTP console looks like this:
![無題](https://user-images.githubusercontent.com/63999713/99389655-b5bec900-291a-11eb-8cab-f58438d0d03b.png)

**Comment by kaorahi** [comment]
Hmm... Would you try 1 and/or 2?

1. Download [Leela 0.11.0 engine only](https://sjeng.org/dl/Leela0110GTP.zip) from https://sjeng.org/leela.html and use Leela0110GTP.exe (not Leela0110GTP_OpenCL.exe) in it.
2. Increase `LEELA0110_PONDERING_INTERVAL_MILLIS` in Leelaz.java (line 106) to `2000` or more. It is the interval of screen updating (milliseconds).

**Comment by hope366** [comment]
I keep the lizzie 0.7.2 folder and update the files in the folder individually.
The following is the content, but when I try it in this folder, the candidate move of Leela 0.11.0 is not displayed.
<img src="https://user-images.githubusercontent.com/63999713/99393427-a9d60580-2920-11eb-8cbb-5dd6f4927491.png" width="70%">
The screenshot below shows lizzie 0.7.4 downloaded and barely tampered with, but when I tried it in this situation, I saw a candidate for Leela 0.11.0.
<img src="https://user-images.githubusercontent.com/63999713/99393719-12bd7d80-2921-11eb-877c-ed313748eb64.png" width="70%">

"Lizzie-0110.jar" has most of the recent PR applied, and "lizzie-leela_nonzero_on074.jar" is a compilation of https://github.com/featurecat/lizzie/tree/f8c43713709b84c1e39b9790a07ef1bd28702d87.
Neither jar file works in the upper folder, it works in the lower folder.
I still don't know where the problem is, so I'll investigate.

**Comment by hope366** [comment]
I tried the screen update interval at 2000 or 3000, but it didn't work.
I tried swapping Leela0110GTP.exe and Leela0110GTP_OpenCL.exe, but it didn't work either.
Apparently the problem is in config.txt. It seems to work if you use config.txt which is working well.
I'd like to check where in config.txt you can find a hint to solve the problem.

**Comment by kaorahi** [comment]
I noticed the candidate moves disappear if I click "showPolicy" in the tool bar.

BTW, I pushed a3230766.

**Comment by hope366** [comment]
I finally figured out where the problem was in cofig.txt.
> "show-bestmoves-by-hold": true,

If this setting is "false", Leela0110 will not display candidates. The default is "true", but I like "false" so I usually do that, but it seems to be incompatible with Leela0110.
Is it possible to rewrite the code so that it works well even if this setting is false?

**Comment by hope366** [comment]
I tried [`a323076`](https://github.com/featurecat/lizzie/commit/a32307665d89e052133cb9ab82783aa1645d5a62), but when I click "show Policy" on the toolbar, the candidates disappear ...

**Comment by kaorahi** [comment]
thx for testing. a3230766 is not for "showPolicy". Please read the commit log. :)

...and I pushed further commits to https://github.com/kaorahi/lizzie/tree/leela_nonzero_on074 .

**Comment by hope366** [comment]
Oh, it seems that I made a mistake because I didn't check the contents of the log properly.
By making Leela 0.11.0 available, it means that the use of Leela Zero has been adversely affected.
It was confirmed that the problem was improved by applying [`a323076`](https://github.com/featurecat/lizzie/commit/a32307665d89e052133cb9ab82783aa1645d5a62).

**Comment by hope366** [comment]
I tried using [Support "showPolicy" in the tool bar for Leela 0.11.0](https://github.com/kaorahi/lizzie/commit/416eaae40215f2803fc2f3ff76475b743f1e3981) in my master, but it doesn't seem to work. ..
Only MoveData.java has changed, right?
https://github.com/kaorahi/lizzie/tree/leela_nonzero_on074 itself is working.
Is there a conflict with other PR?

**Comment by hope366** [comment]
The policy network has been successfully displayed. But it is a momentary thing. It will disappear quickly and you will not be able to see it if pondering is turned on.
Specifically, with pondering turned off, quickly press the spacebar twice. Repeat this many times. Then the policy network will only appear if the timing coincides with when it appears.
LEELA0110_PONDERING_INTERVAL_MILLIS = 1000
This setting has never been successful.
LEELA0110_PONDERING_INTERVAL_MILLIS = 10
This setting often seems to succeed.
There seems to be no change in what is displayed on the GTP console when the policy network is displayed and when it is not.
![無題2](https://user-images.githubusercontent.com/63999713/99558121-bcc30580-2a06-11eb-9efa-2f2e7aeb6a48.png)

**Comment by hope366** [comment]
It is a state of the GTP console when the engine is Leela 0.11.0, but it seems that the displayed contents alternate every time the display ⇔ non-display is switched.
This is not a problem specific to Leela 0.11.0, the same thing happens if the engine is KataGo.
<img src="https://user-images.githubusercontent.com/63999713/99559099-c1d48480-2a07-11eb-86c8-9a7717ee7be5.png" width=45%> <img src="https://user-images.githubusercontent.com/63999713/99559131-c7ca6580-2a07-11eb-9a3c-edca568aa963.png" width=45%>

**Comment by hope366** [comment]
I was having trouble with the policy network not being displayed on the Leela0110, but when I carefully rewrote the code from the beginning, it worked. I think there was a rewriting mistake somewhere.I'm sorry for making a noise.
Next, let me tell you what I noticed about Leela0110.
* When pondering is turned off, the displayed policy network disappears. When pondering is turned on, it will be displayed again soon.
* Another point, I tried `LEELA0110_PONDERING_INTERVAL_MILLIS = 100`, but if I keep the pondering on in the same situation, the analysis speed will drop significantly at a fairly early stage.
The default "1000" seems to be okay.
* If you press the "N" key to play against Leela 0.11.0, Leela thinks even when it's your opponent's turn.
It is solved by adding "--noponder". However, this causes the analysis mode to stop working.
* When playing a game with Leela with the "N" key, it is stable at about 10000 visits / s, but in analysis mode it is only about 200 ~ 300 visits / s. Moreover, the blur is large.

**Comment by kaorahi** [comment]
49140744 should fix the first one. I can't or won't fix the others. This is just a quick hack. Please don't expect much.

Anyway, the previous post gives us a nice list of the limitations of this implementation. Thanks for your reports!

**Comment by hope366** [comment]
Thank you for writing [`4914074`](https://github.com/featurecat/lizzie/commit/491407441d7dacefe59b3f0729151e5ad8da547b).
I dared to find a small problem, but I think it's still convenient enough.
Thank you for making Leela 0.11.0 available!

**Comment by kaorahi** [comment]
Leela 0.11.0 is opensource now. We can modify it as follows so that it works on normal Lizzie without performance loss.

https://github.com/kaorahi/Leela/tree/lz-analyze

**Comment by hope366** [comment]
It seems that automatic analysis is not possible, but is it possible by applying [https://github.com/kaorahi/Leela/tree/lz-analyze](https://github.com/kaorahi/Leela/tree/lz-analyze)?
I wanted to use it, but I can't do it so far because I don't know how to compile Leela.
Is there a good way to set the engine to Leela in lizzie and enable automatic analysis?

**Comment by kaorahi** [comment]
Auto-analysis itself has problems that are not related to this patch.

1. Lizzie ignores auto-analysis silently when we are at the end of the game. So I added a message in #842.
2. In my environment, auto-analysis is stalled even in Lizzie 0.7.4 with KataGo. It doesn't happen in patched_0.7.4 (#798). cf. https://github.com/featurecat/lizzie/issues/825#issuecomment-754577431

**Comment by hope366** [comment]
I haven't done a lot of experimentation, but in my environment the automatic analysis seems to work well when using KataGo with Lizzie-v 0.7.4 (official version).
Of course, patched_0.7.4 (# 798) also works fine.
The problem is when I set Leela on the engine, and when I run the automatic analysis, it keeps analyzing the current situation forever, just like when I turned on pondering.

**Comment by kaorahi** [comment]
Hmm... I cannot reproduce your issue. Anyway, this patch is needless for me now and I have little motivation to improve it.

**Comment by hope366** [comment]
OK. I will think for myself that I can somehow take it for the better. Thank you.
